name: Update the Articles
run-name: Update the Articles
on:
  schedule: # run workflow based on schedule
    - cron: "6 5 1-25 12 *" # from the 1. December till 25. December every day at 5:06am (avoid load at full hours)

  workflow_dispatch: # allow to manually start the workflow

  push:
    # (disabled) run on push, be carefull with this setting
    # as the workflow should only be triggered at a rate lower than
    # 4 times a hour to keep traffic on aoc site low
jobs:
  update:
    runs-on: ubuntu-latest
