name: Create README file

on:
  push:
    branches:
      - main # Trigger this action on push to the main branch
  pull_request:
    branches:
      - main # Optionally trigger on pull requests

jobs:
  convert_html_to_markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2 # Check out the repository

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9 # Use the Python version that fits your needs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install html2markdown  # Install the html2markdown library

      - name: Run the HTML to Markdown conversion script
        run: |
          python convert_html_to_markdown.py  # Run the conversion script

      - name: Configure git
        run: |
          git config --global user.name "cowanweks"
          git config --global user.email "cowannwekesa@gmail.com"

      - name: Check Git status
        run: git status

      - name: Commit and push the generated README.md
        run: |
          git add -A README.md
          git commit -m "Update README from HTML"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Automatically provided token for pushing changes

